export type StoreOption = { id: string; name: string };

export const STORES: StoreOption[] = [
  { id: "02", name: "Bandırma Köroğlu" },
  { id: "03", name: "Biga HYS" },
  { id: "04", name: "Erdek Köroğlu" },
  { id: "05", name: "Gönen HYS" },
  { id: "07", name: "Çanakkale Köroğlu" },
  { id: "08", name: "Çanakkale HYS" },
  { id: "09", name: "Balıkesir Köroğlu" },
  { id: "10", name: "Bandırma HYS" },
  { id: "13", name: "Çan HYS" },
  { id: "14", name: "Balıkesir HYS" },
  { id: "17", name: "Bursa HYS" },
  { id: "19", name: "Kemalpaşa HYS" },
  { id: "20", name: "Karacabey HYS" },
  { id: "21", name: "Kemalpaşa HYS Newstyle" },
  { id: "22", name: "İnegöl HYS" },
  { id: "23", name: "Bandırma Wegarden" },
  { id: "24", name: "Çanakkale Köroğlu" },  
  { id: "25", name: "Bandırma HYS Mobilya" },
  { id: "26", name: "Bursa Heyza" },
  { id: "90", name: "Wehomy Koltuk Fabrikası" },
  { id: "91", name: "Wehomy Sunta Fabrikası" },
  { id: "92", name: "HYS Genel Merkez Ofis" },
];
